name: Auto Create PR on Main Push

on:
  push:
    branches: [ main ]

env:
  # Pin CLI version for reproducible builds. Update when upgrading.
  DIFY_CLI_VERSION: "0.5.3"

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CLI tool
        run: |
          mkdir -p $RUNNER_TEMP/bin
          cd $RUNNER_TEMP/bin
          wget -q https://github.com/langgenius/dify-plugin-daemon/releases/download/${DIFY_CLI_VERSION}/dify-plugin-linux-amd64
          chmod +x dify-plugin-linux-amd64

      - name: Get basic info from manifest
        id: get_basic_info
        run: |
          echo "plugin_name=$(yq e '.name' manifest.yaml)" >> $GITHUB_OUTPUT
          echo "version=$(yq e '.version' manifest.yaml)" >> $GITHUB_OUTPUT
          echo "author=$(yq e '.author' manifest.yaml)" >> $GITHUB_OUTPUT

      - name: Package Plugin
        run: |
          PACKAGE_NAME="${{ steps.get_basic_info.outputs.plugin_name }}-${{ steps.get_basic_info.outputs.version }}.difypkg"
          $RUNNER_TEMP/bin/dify-plugin-linux-amd64 plugin package . -o "$PACKAGE_NAME"

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.get_basic_info.outputs.author }}/dify-plugins
          path: dify-plugins
          token: ${{ secrets.PLUGIN_ACTION }}
          fetch-depth: 1
          persist-credentials: true

      - name: Prepare and push to fork
        run: |
          PACKAGE_NAME="${{ steps.get_basic_info.outputs.plugin_name }}-${{ steps.get_basic_info.outputs.version }}.difypkg"

          mkdir -p dify-plugins/${{ steps.get_basic_info.outputs.author }}/${{ steps.get_basic_info.outputs.plugin_name }}
          mv "$PACKAGE_NAME" dify-plugins/${{ steps.get_basic_info.outputs.author }}/${{ steps.get_basic_info.outputs.plugin_name }}/

          cd dify-plugins

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git fetch origin main
          git checkout main
          git pull origin main

          BRANCH_NAME="bump-${{ steps.get_basic_info.outputs.plugin_name }}-plugin-${{ steps.get_basic_info.outputs.version }}"
          git checkout -b "$BRANCH_NAME"

          git add .
          git commit -m "bump ${{ steps.get_basic_info.outputs.plugin_name }} plugin to version ${{ steps.get_basic_info.outputs.version }}"

          git push -u origin "$BRANCH_NAME"

      - name: Create PR via GitHub API
        env:
          GH_TOKEN: ${{ secrets.PLUGIN_ACTION }}
        run: |
          for i in 1 2 3; do
            gh pr create \
              --repo langgenius/dify-plugins \
              --head "${{ steps.get_basic_info.outputs.author }}:bump-${{ steps.get_basic_info.outputs.plugin_name }}-plugin-${{ steps.get_basic_info.outputs.version }}" \
              --base main \
              --title "bump ${{ steps.get_basic_info.outputs.plugin_name }} plugin to version ${{ steps.get_basic_info.outputs.version }}" \
              --body "bump ${{ steps.get_basic_info.outputs.plugin_name }} plugin package to version ${{ steps.get_basic_info.outputs.version }}

              Changes:
              - Updated plugin package file" && break || sleep 5
          done
